# Use postgres/example user/password credentials
version: '3.1'

services:
  #https://hub.docker.com/_/postgres
  pgdb:
    container_name: pgdb
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - postgressNetwork
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - postgressNetwork

  #https://hub.docker.com/r/dpage/pgadmin4/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports: 
      - 5050:80
    networks: 
      - postgressNetwork

networks:
  postgressNetwork:
    driver: bridge    
    
volumes:
  db-data: