version: '3'
services:
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
   kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601

   packetbeat:
    image: docker.elastic.co/beats/packetbeat:6.4.2
    container_name: packetbeat
    cap_add: ['NET_RAW', 'NET_ADMIN']
    network_mode: host
    command: -e -E 'output.elasticsearch.hosts=["localhost:9200"]'
    depends_on: ['elasticsearch', 'kibana']
   logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    cap_add: ['NET_RAW', 'NET_ADMIN']
    network_mode: host
    command: -e -E 'output.elasticsearch.hosts=["localhost:9200"]'
    depends_on: ['elasticsearch', 'kibana']
  
volumes:
  esdata1:
    driver: local
  