version: '3.1'
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  mongo-gui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password 
networks:
  mongoNetwork:
    driver: bridge   

volumes: 
  mongodb-data:

#vs code : mongodb://root:password@127.0.0.1:27017


    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
#docker run -d -p 127.0.0.1:27017:27017 --name mymongo -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=password mongo
#docker run -it --rm --link mymongo:mongo mongo mongo --host mongo -u root -p password --authenticationDatabase admin mymongo


#docker run -d -p 127.0.0.1:27017:27017 --name mymongo mongo
#docker run -it --rm --link mymongo:mongo mongo mongo --host mongo -u root -p password --authenticationDatabase admin mymongo
